[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/",
  "forge-std/=lib/forge-std/src/",
  "foundry-devops/=lib/foundry-devops/src/"
]

ffi = true

[dependencies]
forge-std = "github:foundry-rs/forge-std@v1.9.1"
foundry-devops = "github:Cyfrin/foundry-devops@0.1.0"
