[profile.default]
src = "src"
out = "out"
libs = ["libs"]

remappings = [
  "chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "@chainlink/=lib/chainlink/"
]
ffi = true
[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std" }
foundry-devops = { git = "https://github.com/Cyfrin/foundry-devops" }
chainlink = { git = "https://github.com/smartcontractkit/chainlink" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
