name: Foundry CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        run: curl -L https://foundry.paradigm.xyz | bash && foundryup

      - name: Install dependencies
        run: forge install

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test -vvv
